In [23]:
import pandas as pd

df = pd.DataFrame({
    'testcolumn': range(11)
})

df

    testcolumn
0            0
1            1
2            2
3            3
4            4
5            5
6            6
7            7
8            8
9            9
10          10

In [ ]:
#Question 1
df.loc[0:10]
#Answer: It does not return 10 rows, it returns 11 rows.
#Rows by index labels. Index labels named 0,...10.

    Test Column
0             0
1             1
2             2
3             3
4             4
5             5
6             6
7             7
8             8
9             9
10           10

In [ ]:
#Question 2
df.iloc[0:10]
#Answer: It returns 10 rows, not 11.
#Selects rows by position: positions 0 through 9; position 10 is excluded.
#Position 0 means the first row, regardless of its index label.
#df.iloc[0:10] gives the same result as df[0:10] in Question 4.
#.iloc explicitly selects by position and can also select columns:
#df.iloc[0:10, 0:2] selects the first 10 rows and up to the first 2 columns.

   Test Column
0            0
1            1
2            2
3            3
4            4
5            5
6            6
7            7
8            8
9            9

In [ ]:
#Question 3
modified_df = df.testcolumn.map(lambda p: p +1)
display(modified_df)
display(df)
#The dataframe did not change.

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
Name: testcolumn, dtype: int64

    testcolumn
0            0
1            1
2            2
3            3
4            4
5            5
6            6
7            7
8            8
9            9
10          10

In [ ]:
#Question 4
df[0:10]
#Answer: It returns 10 rows, not 11.
#This integer slice selects rows at positions 0 through 9, excluding 10.
#It gives the same result as df.iloc[0:10] in Question 2.
#Unlike df.loc[0:10], it does not include the row with index label 10 here.
#df[...] has other meanings depending on what is inside the brackets:
#df['testcolumn'] selects a column rather than slicing rows.

   testcolumn
0           0
1           1
2           2
3           3
4           4
5           5
6           6
7           7
8           8
9           9

In [28]:
import pandas as pd

df = pd.DataFrame({
    'date': ['2007-03-02', '2007-03-22', '2007-04-06']
})

print(df['date'].dtype)

df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')

print(df['date'].dtype)

object
datetime64[ns]